package ticker

// HockeyAliases maps alternate spellings to canonical team names.
// Ported from HFTKalshi/Executables/LiveModeling/Hockey/team_name_aliases.py.
var HockeyAliases = map[string]string{
	// AHL GoalServe abbreviations
	"wilkes barre-scranton penguins":  "wilkes-barre scranton penguins",
	"wilkes-barre/scranton penguins":  "wilkes-barre scranton penguins",
	"wilkes-barre/scranton":           "wilkes-barre scranton penguins",
	"wilkes-barre scranton":           "wilkes-barre scranton penguins",
	"wbs penguins":                    "wilkes-barre scranton penguins",
	"her bears":                       "hershey bears",
	"bel senators":                    "belleville senators",
	"spr thunderbirds":                "springfield thunderbirds",
	"ia wild":                         "iowa wild",
	"cle monsters":                    "cleveland monsters",
	"lv phantoms":                     "lehigh valley phantoms",
	"col eagles":                      "colorado eagles",
	"chi wolves":                      "chicago wolves",
	"mil admirals":                    "milwaukee admirals",
	"roc icehogs":                     "rockford icehogs",
	"roc americans":                   "rochester americans",
	"tor marlies":                     "toronto marlies",
	"lav rocket":                      "laval rocket",
	"man moose":                       "manitoba moose",
	"abbo canucks":                    "abbotsford canucks",
	"abb canucks":                     "abbotsford canucks",
	"bak condors":                     "bakersfield condors",
	"bri islanders":                   "bridgeport islanders",
	"cal wranglers":                   "calgary wranglers",
	"cha checkers":                    "charlotte checkers",
	"cv firebirds":                    "coachella valley firebirds",
	"gr griffins":                     "grand rapids griffins",
	"gra griffins":                    "grand rapids griffins",
	"har wolf pack":                   "hartford wolf pack",
	"har wolfpack":                    "hartford wolf pack",
	"hen silver knights":              "henderson silver knights",
	"hnd silver knights":              "henderson silver knights",
	"ont reign":                       "ontario reign",
	"pro bruins":                      "providence bruins",
	"sd gulls":                        "san diego gulls",
	"sj barracuda":                    "san jose barracuda",
	"tex stars":                       "texas stars",
	"tuc roadrunners":                 "tucson roadrunners",
	"uti comets":                      "utica comets",
	"syr crunch":                      "syracuse crunch",

	// NHL
	"st louis blues":    "st. louis blues",
	"stl blues":         "st. louis blues",
	"mon canadiens":     "montreal canadiens",
	"mtl canadiens":     "montreal canadiens",
	"tb lightning":      "tampa bay lightning",
	"tbl lightning":     "tampa bay lightning",
	"la kings":          "los angeles kings",
	"vgk golden knights": "vegas golden knights",
	"vegas knights":     "vegas golden knights",
	"was capitals":      "washington capitals",
	"wsh capitals":      "washington capitals",
	"cbj blue jackets":  "columbus blue jackets",
	"nyi islanders":     "new york islanders",
	"nyr rangers":       "new york rangers",
	"nj devils":         "new jersey devils",
	"ari coyotes":       "arizona coyotes",
	"ana ducks":         "anaheim ducks",
	"bos bruins":        "boston bruins",
	"buf sabres":        "buffalo sabres",
	"cgy flames":        "calgary flames",
	"car hurricanes":    "carolina hurricanes",
	"chi blackhawks":    "chicago blackhawks",
	"col avalanche":     "colorado avalanche",
	"dal stars":         "dallas stars",
	"det red wings":     "detroit red wings",
	"edm oilers":        "edmonton oilers",
	"fla panthers":      "florida panthers",
	"min wild":          "minnesota wild",
	"nsh predators":     "nashville predators",
	"ott senators":      "ottawa senators",
	"phi flyers":        "philadelphia flyers",
	"pit penguins":      "pittsburgh penguins",
	"sj sharks":         "san jose sharks",
	"sea kraken":        "seattle kraken",
	"tor maple leafs":   "toronto maple leafs",
	"uth hockey club":   "utah mammoth",
	"utah hc":           "utah mammoth",
	"utah hockey club":  "utah mammoth",
	"van canucks":       "vancouver canucks",
	"wpg jets":          "winnipeg jets",

	// KHL
	"tractor chelyabinsk": "traktor chelyabinsk",
	"cska moskva":         "cska moscow",
	"dinamo minsk":        "dynamo minsk",
	"dinamo moscow":       "dynamo moscow",
	"dinamo moskva":       "dynamo moscow",
	"dynamo moskva":       "dynamo moscow",
	"spartak moskva":      "spartak moscow",
	"ska st. petersburg":  "ska saint petersburg",
	"ska st petersburg":   "ska saint petersburg",
	"barys nur-sultan":    "barys astana",
	"lada tolyatti":       "lada togliatti",
	"vityaz moscow region": "vityaz podolsk",
	"amur":         "amur khabarovsk",
	"khabarovsk":   "amur khabarovsk",
	"sibir":        "sibir novosibirsk",
	"novosibirsk":  "sibir novosibirsk",
	"ak bars":      "ak bars kazan",
	"avangard":     "avangard omsk",
	"avtomobilist": "avtomobilist yekaterinburg",
	"yekaterinburg": "avtomobilist yekaterinburg",
	"barys":        "barys astana",
	"cska":         "cska moscow",
	"sochi":        "hc sochi",
	"kunlun":       "kunlun red star",
	"shanghai":     "kunlun red star",
	"lada":         "lada togliatti",
	"togliatti":    "lada togliatti",
	"tolyatti":     "lada togliatti",
	"lokomotiv":    "lokomotiv yaroslavl",
	"yaroslavl":    "lokomotiv yaroslavl",
	"metallurg":    "metallurg magnitogorsk",
	"magnitogorsk": "metallurg magnitogorsk",
	"neftekhimik":  "neftekhimik nizhnekamsk",
	"nizhnekamsk":  "neftekhimik nizhnekamsk",
	"niznekamsk":   "neftekhimik nizhnekamsk",
	"salavat yulaev": "salavat yulaev ufa",
	"salavat ufa":    "salavat yulaev ufa",
	"ufa":            "salavat yulaev ufa",
	"severstal":      "severstal cherepovets",
	"cherepovets":    "severstal cherepovets",
	"ska":            "ska saint petersburg",
	"spartak":        "spartak moscow",
	"torpedo":        "torpedo nizhny novgorod",
	"nizhny novgorod": "torpedo nizhny novgorod",
	"traktor":        "traktor chelyabinsk",
	"tractor":        "traktor chelyabinsk",
	"vityaz":         "vityaz podolsk",
	"podolsk":        "vityaz podolsk",
	"admiral":        "admiral vladivostok",
	"vladivostok":    "admiral vladivostok",

	// SHL (Sweden) — diacritics stripped by Normalize, so ä→a/ö→o keys are unnecessary
	"brynas": "brynas if",
	"djurgarden": "djurgardens if",
	"farjestad": "farjestad bk",
	"frolunda": "frolunda hc",
	"linkoping": "linkoping hc",
	"lulea": "lulea hf",
	"orebro": "orebro hk",
	"rogle": "rogle bk",
	"skelleftea": "skelleftea aik",
	"timra": "timra ik",
	"vaxjo": "vaxjo lakers",
	"ik oskarshamn": "oskarshamn",
	"leksands if": "leksand", "leksands": "leksand",

	// Liiga (Finland)
	"porin assat": "assat",
	"mikkelin jukurit": "jukurit",
	"hpk hameenlinna": "hpk",
	"helsingfors ifk": "hifk", "hifk helsinki": "hifk",
	"jyp jyvaskyla": "jyp",
	"kalpa kuopio": "kalpa",
	"kookoo kouvola": "kookoo",
	"karpat oulu": "karpat", "oulun karpat": "karpat",
	"lahti pelicans": "pelicans", "lahden pelicans": "pelicans",
	"lukko rauma": "lukko",
	"saipa lappeenranta": "saipa",
	"vaasan sport": "sport", "sport vaasa": "sport",
	"hc tps": "tps", "hc tps turku": "tps", "tps turku": "tps",
	"tappara tampere": "tappara",
	"ilves tampere": "ilves",

	// Czech Extraliga (ELH)
	"hc sparta praha":          "sparta praha",
	"sparta prague":            "sparta praha",
	"hc sparta prague":         "sparta praha",
	"bk mlada boleslav":        "mlada boleslav",
	"hc kometa brno":           "kometa brno",
	"hc ocelari trinec":        "trinec",
	"hc ocelar trinec":         "trinec",
	"ocelari trinec":           "trinec",
	"hc trinec":                "trinec",
	"hc dynamo pardubice":      "pardubice",
	"dynamo pardubice":         "pardubice",
	"hc vitkovice ridera":      "vitkovice",
	"hc vitkovice":             "vitkovice",
	"hc energie karlovy vary":  "karlovy vary",
	"hc energie":               "karlovy vary",
	"hc verva litvinov":        "litvinov",
	"hc litvinov":              "litvinov",
	"hc motor ceske budejovice": "ceske budejovice",
	"hc motor":                 "ceske budejovice",
	"hc olomouc":               "olomouc",
	"mountfield hk":            "hradec kralove",
	"hc hradec kralove":        "hradec kralove",
	"hc skoda plzen":           "plzen",
	"hc plzen":                 "plzen",
	"hc bili tygri liberec":    "liberec",
	"hc liberec":               "liberec",
	"bili tygri liberec":       "liberec",
	"psg berani zlin":          "zlin",
	"hc zlin":                  "zlin",
	"hc kladno":                "kladno",
	"rytiri kladno":            "kladno",

	// Olympic
	"usa": "united states", "united states of america": "united states",
	"usa w": "united states w", "united states of america w": "united states w",
	"czechia": "czech republic", "czechia w": "czech republic w",
	"korea republic": "south korea", "korea republic w": "south korea w",
	"oar": "russia",
}
